### ISSUE TITLE
No more release?

### ISSUE THREAD

**Issue by samzlab** [antrix1/arenamaster-addon#8]
The database is not updated in the last 6 days. Tought it's automated.

Can you please update? We are early in the season and everyone pushing, the ratings changes rapidly and we have to lookup manually a CR's.

Thank you very much!

**Comment by antrix1** [comment]
Hi @samzlab. It is automated, but the EU export has become too large that GitHub API no longer accepts the file of that size, and the webserver is having memory issues. I'm working on optimizing the export process and updating the data format to reduce the size. I'm not sure when that will happen, but most likely by next week. 

I'm sorry for the inconvenience, and please bear with me until it's fixed. Make sure to join the Discord through the web app, as I'll be posting an announcement when the issue is resolved.

**Comment by antrix1** [comment]
@samzlab The addon format has been updated and the updates should continue coming in daily. Thanks for the patience!
